const TIME_INTERVAL_SECONDS = 10000;
const TWELVE_HOUR_INTERVAL_SECONDS = 43200000;
const FUEL_TWENTY_HOUR_INTERVAL_SECONDS = 86400000;
const COOLANT_TEMP_WARN_LEVEL_1 = 100;
const COOLANT_TEMP_WARN_LEVEL_2 = 110;
const PLACEHOLDER_PINNO = "{pinno}";
const PLACEHOLDER_TEMPERATURE = "{temperature}";
const COOLANT_TEMP_NOTIFICATION_TEMPLATE_HIGH = "Critical alert !! Coolant temperature for vehicle " + + PLACEHOLDER_PINNO + " has  reached  " + PLACEHOLDER_TEMPERATURE + " degrees. Pls stop your vehicle and address the issue. AUGTRN"
const COOLANT_TEMP_NOTIFICATION_TEMPLATE_MEDIUM = "Warning alert !! Coolant temperature for vehicle " + PLACEHOLDER_PINNO + " has  reached  " + PLACEHOLDER_TEMPERATURE + " degrees. Pls address the issue. AUGTRN";
const PLACEHOLDER_MOBILENO = "{mobileno}";
const PLACEHOLDER_MESSAGE = "{message}";
const SMS_SERVICE_HOST = "prpsms.co.in";
const SMS_SERVICE_PATH = "/API/SendMsg.aspx?uname=20210102&pass=9Bat94Zr&send=AUGTRN&dest={mobileno}&msg={message}";
const COOLANT_TEMP_NOTIFICATION_TYPE_HIGH = "coolantNotificationHighTime";
const COOLANT_TEMP_NOTIFICATION_TYPE_MEDIUM = "coolantNotificationMediumTime";

//Engine Oil Pressure (Bar)

const ENGINE_OIL_PRESSURE_WARN_LEVEL = 1;
const PLACEHOLDER_BAR = "{bar}";
const ENGINE_OIL_PRESSURE_NOTIFICATION_TEMPLATE_HIGH = "Critical Alert !! Engine Oil Pressure for vehicle  " + PLACEHOLDER_PINNO + "  has reached " + PLACEHOLDER_BAR + " bar. Pls stop your vehicle and address the issue. AUGTRN";
const ENGINE_OIL_PRESSURE_NOTIFICATION_TYPE_HIGH = "oilpressureNotificationHighTime";

// Fuel Level
const FUEL_LEVEL_WARN_LEVEL_1 = "Reserve";
const FUEL_LEVEL_WARN_LEVEL_2 = "Empty";
const PLACEHOLDER_LEVEL = "{level}";
const FUEL_LEVEL_NOTIFICATION_TEMPLATE_HIGH = "Critical Alert !! Fuel Level for vehicle " + PLACEHOLDER_PINNO + "  is " + PLACEHOLDER_LEVEL + " . Pls fill fuel and then drive your vehicle. AUGTRN";
const FUEL_LEVEL_NOTIFICATION_TEMPLATE_MEDIUM = "Warning Alert !! Fuel Level for vehicle  " + PLACEHOLDER_PINNO + " is in " + PLACEHOLDER_LEVEL + " . Pls fill fuel and then drive your vehicle AUGTRN";
const FUEL_LEVEL_NOTIFICATION_TYPE_HIGH = "fuellevelNotificationHighTime";
const FUEL_LEVEL_NOTIFICATION_TYPE_MEDIUM = "fuellevelNotificationMediumTime";

// Hydraulic Filter choke
const HYDRAULIC_FILTER_CHOKE_WARN_LEVEL = "CHOKE";
const PLACEHOLDER_CHOKE = "{value}";
const HYDRAULIC_FILTER_CHOKE_NOTIFICATION_TEMPLATE_HIGH = "Critical Alert !! Hydraulic oil filter for vehicle " + PLACEHOLDER_PINNO + " is " + PLACEHOLDER_CHOKE + " . Pls replace the filter. AUGTRN";
const HYDRAULIC_FILTER_CHOKE_NOTIFICATION_TYPE_HIGH = "HydraulicFilterchokeNotificationHighTime";

// LOW BATTERY VOLTAGE (v)
const LOW_BATTERY_VOLTAGE_WARN_LEVEL_1 = 8;
const LOW_BATTERY_VOLTAGE_WARN_LEVEL_2 = 10;
const PLACEHOLDER_VOLTAGE = "{volt}";
const LOW_BATTERY_VOLTAGE_NOTIFICATION_TEMPLATE_MEDIUM = "Warning Alert !! Battery voltage for vehicle " + PLACEHOLDER_PINNO + "  has reached  " + PLACEHOLDER_VOLTAGE + " volts. Pls get your vehicle battery recharged. AUGTRN";
const LOW_BATTERY_VOLTAGE_NOTIFICATION_TYPE_MEDIUM = "lowbatteryvoltagelNotificationMediumTime";

module.exports = {
    //COOLANT_TEMP
    TIME_INTERVAL_SECONDS,
    COOLANT_TEMP_WARN_LEVEL_1,
    COOLANT_TEMP_WARN_LEVEL_2,
    PLACEHOLDER_PINNO,
    PLACEHOLDER_TEMPERATURE,
    COOLANT_TEMP_NOTIFICATION_TEMPLATE_MEDIUM,
    COOLANT_TEMP_NOTIFICATION_TEMPLATE_HIGH,
    PLACEHOLDER_MOBILENO,
    PLACEHOLDER_MESSAGE,
    SMS_SERVICE_HOST,
    SMS_SERVICE_PATH,
    COOLANT_TEMP_NOTIFICATION_TYPE_HIGH,
    COOLANT_TEMP_NOTIFICATION_TYPE_MEDIUM,
    TWELVE_HOUR_INTERVAL_SECONDS,
    FUEL_TWENTY_HOUR_INTERVAL_SECONDS,


    //OIL PRESSURE
    ENGINE_OIL_PRESSURE_WARN_LEVEL,
    ENGINE_OIL_PRESSURE_NOTIFICATION_TEMPLATE_HIGH,
    ENGINE_OIL_PRESSURE_NOTIFICATION_TYPE_HIGH,
    PLACEHOLDER_BAR,

    //FUEL LEVEL
    FUEL_LEVEL_WARN_LEVEL_1,
    FUEL_LEVEL_WARN_LEVEL_2,
    PLACEHOLDER_LEVEL,
    FUEL_LEVEL_NOTIFICATION_TEMPLATE_HIGH,
    FUEL_LEVEL_NOTIFICATION_TEMPLATE_MEDIUM,
    FUEL_LEVEL_NOTIFICATION_TYPE_HIGH,
    FUEL_LEVEL_NOTIFICATION_TYPE_MEDIUM,

    //Hydraulic Filter choke
    HYDRAULIC_FILTER_CHOKE_WARN_LEVEL,
    PLACEHOLDER_CHOKE,
    HYDRAULIC_FILTER_CHOKE_NOTIFICATION_TEMPLATE_HIGH,
    HYDRAULIC_FILTER_CHOKE_NOTIFICATION_TYPE_HIGH,

    
//  LOW BATTERY VOLTAGE (v)
    LOW_BATTERY_VOLTAGE_WARN_LEVEL_1,
    LOW_BATTERY_VOLTAGE_WARN_LEVEL_2,
    PLACEHOLDER_VOLTAGE,
    LOW_BATTERY_VOLTAGE_NOTIFICATION_TEMPLATE_MEDIUM,
    LOW_BATTERY_VOLTAGE_NOTIFICATION_TYPE_MEDIUM,
    
}